### PR TITLE
Archlinux/Manjaro Support Added

### PR DESCRIPTION
**Pull request by KkiEEoDyssey**
Added Checks to have the setup work properly for archlinux and manjaro as well as fixed up build.py to point to the correct path for wine.

### CODE REVIEW

**Comment by 3ct0s** [comment]
I will be testing the Debian side of the code to see if the setup works as expected. Maybe @Hazed2004 can test the arch code for the setup?

**Comment by Hazed2004** [comment]
> I will be testing the Debian side of the code to see if the setup works as expected. Maybe @Hazed2004 can test the arch code for the setup?

yeah man, I'll test it on arch based Linux

**Comment by 3ct0s** [comment]
Encountered problems with the building and the setup file itself. I made some modifications to the setup file and I am still working on the building issue.
`wine: cannot find L"/root/.wine/drive_c/users/root/AppData/Local/Programs/Python/Python38-32/Scripts/pyinstaller.exe"`

**Comment by 3ct0s** [comment]
I was having issues working with the distro.id() function as it was giving me false positives. Can @KkiEEoDyssey or @Hazed2004 try the new updated setup scripts and the builder and let me know if it works properly on Arch? If you believe something needs to be changed please commit your new changes and I will have a look.

**Pull request merged**
